---
branches:
  - name: main
# TODO: Remove; Might be useful to have some debug when attempting the first releases
debug: true
# TODO: Remove; Attempt a dry run release before a real one
dryRun: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
